
rmdir /s /q bin
rmdir /s /q obj

rmdir /s /q automode\bin\
rmdir /s /q automode\obj\

rmdir /s /q VisionProcessForm\bin\
rmdir /s /q VisionProcessForm\obj\

rmdir /s /q VisionProcessing\bin\
rmdir /s /q VisionProcessing\obj\

rmdir /s /q VisionModule\bin\
rmdir /s /q VisionModule\obj\

rmdir /s /q iomode\bin\
rmdir /s /q iomode\obj\

rmdir /s /q user\bin\
rmdir /s /q user\obj\

rmdir /s /q History\bin\
rmdir /s /q History\obj\

rmdir /s /q Common\bin\
rmdir /s /q Common\obj\

rmdir /s /q ImageAcquisition\bin\
rmdir /s /q ImageAcquisition\obj\

rmdir /s /q Lighting\bin\
rmdir /s /q Lighting\obj\

rmdir /s /q SharedMemory\bin\
rmdir /s /q SharedMemory\obj\

rmdir /s /q SRMVision\bin\
rmdir /s /q SRMVision\obj\

rmdir /s /q activationform\bin\
rmdir /s /q activationform\obj\

rmdir /s /q svgsetup\bin\
rmdir /s /q svgsetup\obj\

del *.ncb
del *.zip
del *.arj
del *.scc
del *.zip